# Generated by Django 4.1.4 on 2022-12-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_volunteers_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteers',
            name='skills',
            field=models.CharField(max_length=150),
        ),
    ]
