# Generated by Django 4.1.4 on 2022-12-28 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_volunteers_skills'),
    ]

    operations = [
        migrations.DeleteModel(
            name='volunteers',
        ),
    ]
