# Generated by Django 4.1.4 on 2022-12-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='volunteer',
        ),
    ]
