# Generated by Django 4.1.4 on 2022-12-28 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='volunteer',
            new_name='students',
        ),
    ]
